/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Jan 11 16:53:53 2025. */

#include "alarmclock.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SpeechSynthMsg_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, SpeechSynthMsg, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t TimeMsg_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, TimeMsg, hours, hours, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, TimeMsg, minutes, hours, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, TimeMsg, seconds, minutes, 0),
    PB_LAST_FIELD
};

const pb_field_t AlarmMsg_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, AlarmMsg, hours, hours, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, AlarmMsg, minutes, hours, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, AlarmMsg, seconds, minutes, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, AlarmMsg, enabled, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t NeoPixelMsg_fields[6] = {
    PB_FIELD(  1, MESSAGE , REQUIRED, STATIC  , FIRST, NeoPixelMsg, start_color, start_color, &NeoPixelMsg_Color_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, NeoPixelMsg, end_color, start_color, &NeoPixelMsg_Color_fields),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, NeoPixelMsg, brightness, end_color, 0),
    PB_FIELD(  4, UENUM   , REQUIRED, STATIC  , OTHER, NeoPixelMsg, pattern, brightness, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, NeoPixelMsg, delay, pattern, 0),
    PB_LAST_FIELD
};

const pb_field_t NeoPixelMsg_Color_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, NeoPixelMsg_Color, green, green, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, NeoPixelMsg_Color, red, green, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, NeoPixelMsg_Color, blue, red, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(NeoPixelMsg, start_color) < 65536 && pb_membersize(NeoPixelMsg, end_color) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SpeechSynthMsg_TimeMsg_AlarmMsg_NeoPixelMsg_NeoPixelMsg_Color)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for SpeechSynthMsg.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
