/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Jan  6 03:33:51 2025. */

#include "alarm.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Speak_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, Speak, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t Time_fields[4] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Time, hours, hours, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Time, minutes, hours, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Time, seconds, minutes, 0),
    PB_LAST_FIELD
};

const pb_field_t Alarm_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Alarm, hours, hours, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Alarm, minutes, hours, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Alarm, seconds, minutes, 0),
    PB_FIELD(  4, BOOL    , REQUIRED, STATIC  , OTHER, Alarm, enabled, seconds, 0),
    PB_LAST_FIELD
};

const pb_field_t Lighting_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Lighting, color, color, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Lighting, brightness, color, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for Speak.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
