/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Sat Jan 11 16:53:53 2025. */

#ifndef PB_ALARMCLOCK_PB_H_INCLUDED
#define PB_ALARMCLOCK_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _NeoPixelMsg_Pattern {
    NeoPixelMsg_Pattern_COLOR_WIPE = 1,
    NeoPixelMsg_Pattern_THEATRE_CHASE = 2,
    NeoPixelMsg_Pattern_SOLID = 3,
    NeoPixelMsg_Pattern_RAINBOW = 4,
    NeoPixelMsg_Pattern_THEATRE_CHASE_RAINBOW = 5,
    NeoPixelMsg_Pattern_PULSE = 6
} NeoPixelMsg_Pattern;
#define _NeoPixelMsg_Pattern_MIN NeoPixelMsg_Pattern_COLOR_WIPE
#define _NeoPixelMsg_Pattern_MAX NeoPixelMsg_Pattern_PULSE
#define _NeoPixelMsg_Pattern_ARRAYSIZE ((NeoPixelMsg_Pattern)(NeoPixelMsg_Pattern_PULSE+1))

/* Struct definitions */
typedef struct _AlarmMsg {
    uint32_t hours;
    uint32_t minutes;
    uint32_t seconds;
    bool enabled;
/* @@protoc_insertion_point(struct:AlarmMsg) */
} AlarmMsg;

typedef struct _NeoPixelMsg_Color {
    uint32_t green;
    uint32_t red;
    uint32_t blue;
/* @@protoc_insertion_point(struct:NeoPixelMsg_Color) */
} NeoPixelMsg_Color;

typedef struct _SpeechSynthMsg {
    char data[256];
/* @@protoc_insertion_point(struct:SpeechSynthMsg) */
} SpeechSynthMsg;

typedef struct _TimeMsg {
    uint32_t hours;
    uint32_t minutes;
    uint32_t seconds;
/* @@protoc_insertion_point(struct:TimeMsg) */
} TimeMsg;

typedef struct _NeoPixelMsg {
    NeoPixelMsg_Color start_color;
    bool has_end_color;
    NeoPixelMsg_Color end_color;
    uint32_t brightness;
    NeoPixelMsg_Pattern pattern;
    bool has_delay;
    uint32_t delay;
/* @@protoc_insertion_point(struct:NeoPixelMsg) */
} NeoPixelMsg;

/* Default values for struct fields */

/* Initializer values for message structs */
#define SpeechSynthMsg_init_default              {""}
#define TimeMsg_init_default                     {0, 0, 0}
#define AlarmMsg_init_default                    {0, 0, 0, 0}
#define NeoPixelMsg_init_default                 {NeoPixelMsg_Color_init_default, false, NeoPixelMsg_Color_init_default, 0, _NeoPixelMsg_Pattern_MIN, false, 0}
#define NeoPixelMsg_Color_init_default           {0, 0, 0}
#define SpeechSynthMsg_init_zero                 {""}
#define TimeMsg_init_zero                        {0, 0, 0}
#define AlarmMsg_init_zero                       {0, 0, 0, 0}
#define NeoPixelMsg_init_zero                    {NeoPixelMsg_Color_init_zero, false, NeoPixelMsg_Color_init_zero, 0, _NeoPixelMsg_Pattern_MIN, false, 0}
#define NeoPixelMsg_Color_init_zero              {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AlarmMsg_hours_tag                       1
#define AlarmMsg_minutes_tag                     2
#define AlarmMsg_seconds_tag                     3
#define AlarmMsg_enabled_tag                     4
#define NeoPixelMsg_Color_green_tag              1
#define NeoPixelMsg_Color_red_tag                2
#define NeoPixelMsg_Color_blue_tag               3
#define SpeechSynthMsg_data_tag                  1
#define TimeMsg_hours_tag                        1
#define TimeMsg_minutes_tag                      2
#define TimeMsg_seconds_tag                      3
#define NeoPixelMsg_start_color_tag              1
#define NeoPixelMsg_end_color_tag                2
#define NeoPixelMsg_brightness_tag               3
#define NeoPixelMsg_pattern_tag                  4
#define NeoPixelMsg_delay_tag                    5

/* Struct field encoding specification for nanopb */
extern const pb_field_t SpeechSynthMsg_fields[2];
extern const pb_field_t TimeMsg_fields[4];
extern const pb_field_t AlarmMsg_fields[5];
extern const pb_field_t NeoPixelMsg_fields[6];
extern const pb_field_t NeoPixelMsg_Color_fields[4];

/* Maximum encoded size of messages (where known) */
#define SpeechSynthMsg_size                      259
#define TimeMsg_size                             18
#define AlarmMsg_size                            20
#define NeoPixelMsg_size                         54
#define NeoPixelMsg_Color_size                   18

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALARMCLOCK_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
