/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Fri Jan  3 20:44:53 2025. */

#include "hid.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeviceDescriptor_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceDescriptor, iManufacturer, iManufacturer, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, DeviceDescriptor, iProduct, iManufacturer, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, DeviceDescriptor, bMaxPacketSize0, iProduct, 0),
    PB_LAST_FIELD
};

const pb_field_t HIDReport_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, HIDReport, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t InputReport_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, InputReport, data, data, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for HIDReport.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
